name: Publish Canary

on:
  pull_request:
    branches:
      - main
      - '!release_**'
  pull_request_target:
    branches:
      - dev
      - '!release_**'

jobs:
  authorize:
    name: Authorize external pull request
    uses: ./.github/workflows/auth.yml

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      auto-options: '--no-changelog'
      upload_assets: false
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
