name: Publish Canary

on:
  pull_request_target:
    branches:
      - dev
      - master

jobs:
  authorize:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}

    steps:
      - name: Echo
        run: |
          echo "External pull request approved by code owners"
          echo "$GITHUB_REF"
          echo "$GITHUB_SHA"

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
